config/routes.rb
Rails.application.routes.draw do
  root to: "snips#new"
  resources :snips, only: [:new, :index, :create, :show, :edit, :update, :destroy] do
    resources :comments, only: [:new, :create, :show]
  end
end

app/models/comment.rb
class Comment < ActiveRecord::Base

  include ActsAsCommentable::Comment

  belongs_to :commentable, :polymorphic => true

  validates :comment, presence: true

  default_scope -> { order('created_at ASC') }

  # NOTE: install the acts_as_votable plugin if you
  # want user to vote on the quality of comments.
  #acts_as_voteable

  # NOTE: Comments belong to a user
  belongs_to :user
end

app/models/language.rb
class Language < ActiveRecord::Base
end

app/models/snip.rb
class Snip < ActiveRecord::Base
  belongs_to :user
  belongs_to :language
  acts_as_commentable

  validates :name, presence: true
  validates :content, presence: true

end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User
  has_many :snips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :find_snip
  
  def new
    @comment = @snip.comments.new
  end

  def create
    @comment = @snip.comments.new(comment_params)
    @comment.user = current_user

    if @comment.save
      redirect_to snip_path(@snip)
    else
      render "snips/show"
    end
  end

  private

  def find_snip
    @snip = Snip.find(params[:snip_id])
  end

  def comment_params
    params.require(:comment).permit(:title, :comment)
  end

end

app/controllers/snips_controller.rb
class SnipsController < ApplicationController
  before_action :require_login, except: :show

  def index
    @snips = current_user.snips
  end

  def new
    @snip = Snip.new
  end

  def create
    @snip = current_user.snips.new(snip_params)
    if @snip.save
      redirect_to snips_path
    else
      render :new
    end
  end

  def show
    @snip = Snip.find(params[:id])
    @comments = @snip.comments.to_a
    @comment = @snip.comments.new
  end

  def edit
    @snip = current_user.snips.find(params[:id])
  end

  def update
    @snip = current_user.snips.find(params[:id])
    if @snip.update_attributes(snip_params)
      redirect_to @snip
    else
      render :edit
    end
  end

  def destroy
    snip = current_user.snips.find(params[:id])
    snip.destroy!
    redirect_to snips_path
  end

  private

  def snip_params
    params.require(:snip).permit(:name, :description, :language_id, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/comments/_comment.html.erb
<%= div_for comment, class: "panel panel-default" do %>
  <div class="panel-body"><%= simple_format(comment.comment) %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <meta name="ROBOTS" content="NOODP" />
  <meta name="viewport" content="initial-scale=1" />
  <%#
    Configure default and controller-, and view-specific titles in
    config/locales/en.yml. For more see:
    https://github.com/calebthompson/title#usage
  %>
  <title><%= title %></title>
  <%= stylesheet_link_tag :application, media: "all" %>
  <%= csrf_meta_tags %>
</head>
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
   <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
       <%= link_to 'Snippet', snips_path, class: 'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><%= link_to t("snips.index.add"), new_snip_path %><span class="sr-only">(current)</span></li>
        <li><%= link_to t("snips.show.my_snips"), snips_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if signed_in? %>
          <li><p class="navbar-text">Signed in as: <%= current_user.email %></p></li>
          <li><%= button_to 'Sign out', sign_out_path, class: "btn btn-default navbar-btn", method: :delete %></li>
        <% else %>
          <li><%= button_to 'Sign in', sign_in_path, class: "btn btn-default navbar-btn", method: :get %></li>
          <li><p class="navbar-text"></p></li>
          <% if Clearance.configuration.allow_sign_up? %>
            <li><%= button_to 'Sign up', sign_up_path, class: "btn btn-default navbar-btn", method: :get %></li>
          <% end %>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

  <%= render "flashes" -%>
  <%= yield %>
  <%= render "javascript" %>
</html>

app/views/snips/_snip.html.erb
<%= div_for snip, class: "panel panel-default" do %>
  <div class="panel-heading">
    <h3 class="panel-title"><%= link_to snip.name, snip %>
    <%= link_to "Delete", snip, class: "pull-right", method: :delete %>
    </h3>
  </div>
  <div class="panel-body">
    <%= snip.description.blank? ? "..." : snip.description %>
  </div>
<% end %>

app/views/snips/edit.html.erb
<div class="container-fluid">
   <div class="col-md-4">
      <%= simple_form_for(@snip, html: { class: 'form-horizontal' }, wrapper: :horizontal_form) do |f| %>
        <%= f.input :name, placeholder: 'Name for your snip', input_html: { maxlength: 40 }, required: true %>
        <%= f.input :description, placeholder: 'Add description if necessary', input_html: { maxlength: 50 }, required: false %>
        <%= f.association :language, label_method: :lang, collection: Language.all, prompt: "Select language" %>
        <%= f.input :content, as: :text, placeholder: 'Add contents of your snip', required: true %>
        <%= f.button :submit, "Save changes" %>
      <% end %>
    </div>
</div>

app/views/snips/index.html.erb
<div class="col-md-4">
    <% if @snips.empty? %>
      <p>There are no snips yet.</p>
    <% else %>
      <%= render collection: @snips, partial: "snip" %>
    <% end %>
</div>

app/views/snips/new.html.erb
<div class="container-fluid">
   <div class="col-md-4">
      <%= simple_form_for(@snip, html: { class: 'form-horizontal' }, wrapper: :horizontal_form) do |f| %>
        <%= f.input :name, placeholder: 'Name for your snip', input_html: { maxlength: 40 }, required: true %>
        <%= f.input :description, placeholder: 'Add description if necessary', input_html: { maxlength: 50 }, required: false %>
        <%= f.association :language, label_method: :lang, collection: Language.all, prompt: "Select language", selected: "text" %>
        <%= f.input :content, as: :text, placeholder: 'Add contents of your snip', required: true %>
        <%= f.button :submit, t("snips.new.add") %>
      <% end %>
    </div>
</div>

app/views/snips/show.html.erb
<div class="container-fluid">

  <div class="row">
    <div class="col-md-8">
      <p><%= @snip.description %></p>
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title"><%= @snip.name %></h3>
        </div><!--panel-heading-->
        <div class="panel-body">
          <% if @snip.language.lang == "text" %>
            <%= simple_format h(@snip.content) %>
          <% else %>
            <%= CodeRay.scan(@snip.content, @snip.language.lang.to_sym).div(:line_numbers => :table).html_safe %>
          <% end %>
        </div><!--panel-body-->
      </div><!-- panel-primary-->
    </div><!-- col-md8-->
  </div>

  <div class="row">
    <div class="col-md-8">
      <% if @snip.user == current_user %>
        <%= button_to "Edit", edit_snip_path(@snip), class: "btn btn-default", method: :get %>
      <% end %>
    </div>
  </div>

  <div class="row copy-clipboard">
    <div class="col-md-3">
      <div class='input-group'>
        <span class="input-group-btn">
          <button type="button" class="btn btn-default" data-clipboard-target='fe_text'
           data-clipboard-text='Default clipboard text from attribute' id='d_clip_button'>
            <span class="glyphicon glyphicon-copy" aria-hidden="true"></span>
          </button>
        </span>

        <input type="text" class="form-control" id='fe_text' readonly="readonly" value = "<%= snip_url(@snip) %>" >
      </div>
    </div>
  </div>

<script>
  document.addEventListener("DOMContentLoaded", function(event) { 
    $(document).ready(function() {
      var clip = new ZeroClipboard($("#d_clip_button"))
    });
  });


</script>

  <div class ="row new-comment-form">
    <div class="col-md-8">
      <%= simple_form_for [@snip, @comment] do |f| %>
        <%= f.input :comment, placeholder: "Comment" %>
        <%= f.button :submit, t("comments.new.post") %>
      <% end %>
    </div>
  </div>



  <div class ="row">
    <div class="col-md-8">
      <%= render collection: @comments, partial: "comments/comment" %>
    </div>
  </div>
</div>

app/views/users/_form.html.erb
  <div class="form-group">
     <%= form.input :email, type: 'email' %>
  </div>

  <div class="form-group">
    <%= form.input :password %>
  </div>

app/views/users/new.html.erb
<div class="container-fluid">
  <div class="col-md-4">
    <h2><%= t(".title") %></h2>

    <%= simple_form_for @user do |form| %>
      <%= render partial: '/users/form', object: form %>

      <div class="form-group">
        <%= form.button :submit, "Sign up" %>
      </div>
    <% end %>
  </div>
</div>